
# Ansible has some dependencies: http://docs.ansible.com/ansible/intro_installation.html
# Detect if the client has python-apt. If not, install all listed dependencies.  
- name: Install Ansible Dependencies
  hosts: ubuntu
  become: true
  remote_user: ubuntu
  gather_facts: no
  pre_tasks:
    - raw: apt-get update; apt-get -y install python-simplejson python-apt;
###
### End Ansible Dependencies      

- name: apply common configuration to all nodes
  hosts: ubuntu
  become: true
  remote_user: ubuntu

  roles:
    - common
    - sudo
    - swapfile

- name: deploy Stoutsopenvpn OpenVPN role
  hosts: Stoutsopenvpn
  become: true
  remote_user: ubuntu

  roles:
    - iptables-openvpn
    - Stoutsopenvpn
    - makeovpn

- name: check restart status and restart if required
  hosts: ubuntu
  become: true
  remote_user: ubuntu

  roles:
    - rebooter
